export * from './Login/Login'
export * from './Dashboard/Dashboard'
export * from './Register/Register'
export * from './CourseDetails/MyCourses'
export * from './Profile/Profile'
export * from './CourseDetails/CourseDetails'
export * from './Friends/Friends'
export * from './Students/Student'